Repository TinxHQ/wazo-production-sf-config, pull requests merged in 2022-01, with the labels that each got.

#9 reorder wazo-dbms resource.yaml
  resources/resources.yaml
Labels: auto-merge

#10 use latest docker-compose version
  nodepool/elements/wazo/post-install.d/60-docker
Labels: mergeit

#11 inject docker-credentials in VM built
  nodepool/elements/wazo/extra-data.d/50-docker-hub-credentials
  nodepool/elements/wazo/post-install.d/50-docker-credentials
Labels: mergeit

#12 add wazo-codec-opus-open-source
  resources/resources.yaml
Labels: mergeit

#13 resources: make codec-opus unprotected
  resources/resources.yaml
Labels: mergeit, auto-merge

#14 add wazo-python-marshmallow-packaging
  resources/resources.yaml
Labels: auto-merge

#15 resources: add confd-cli
  resources/resources.yaml
Labels: auto-merge
